In [4]:
n = 3

nombres = []
ccs = []
direcciones = []

for i in range(n):
    nombre = input("Nombre: ")
    cc = input("CC: ")
    direccion = input("Dirección: ")

    nombres.append(nombre)
    ccs.append(cc)
    direcciones.append(direccion)

print(nombres)
print(ccs)
print(direcciones)
SLS

Nombre: JHPOJAN
CC: KAKKA
Dirección: KALKAAL
Nombre: LALALLA
CC: LSSLKKS
Dirección: LSSSSK
Nombre: SLSLLSS
CC: LSKLSS
Dirección: SKSKSKS
['JHPOJAN', 'LALALLA', 'SLSLLSS']
['KAKKA', 'LSSLKKS', 'LSKLSS']
['KALKAAL', 'LSSSSK', 'SKSKSKS']


In [5]:

import numpy as np

nombres = ["Juan", "Ana", "Carlos", "María", "Luis"]
frutas = ["manzana", "banana", "naranja", "pera", "fresa"]
edades = [25, 30, 22, 28, 35]

nombres_array = np.array(nombres)
frutas_array = np.array(frutas)
edades_array = np.array(edades)

print("Array de nombres:")
print(nombres_array)

print("Array de frutas:")
print(frutas_array)

print("Array de edades:")
print(edades_array)


Array de nombres:
['Juan' 'Ana' 'Carlos' 'María' 'Luis']
Array de frutas:
['manzana' 'banana' 'naranja' 'pera' 'fresa']
Array de edades:
[25 30 22 28 35]


In [8]:
import numpy as np

frutas = ["manzana", "banana", "naranja"]
nombres = ["Ana", "Luis", "Carlos"]
edades = [25, 30, 35]

# Convertimos las listas en un array 2D vertical (cada lista es una columna)
arr = np.array([frutas, nombres, edades])

# Transponemos para que las listas queden como columnas (vertical)
arr_vertical = arr.T

print("Datos organizados verticalmente:")
print(arr_vertical)




Datos organizados verticalmente:
[['manzana' 'Ana' '25']
 ['banana' 'Luis' '30']
 ['naranja' 'Carlos' '35']]


In [14]:
import numpy as np

lst1 = [10, 20, 30, 40, 50]       # 5 términos
lst2 = [1, 2, 3, 4, 5] # 5 términos

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_add = vctr1 + vctr2[:len(vctr1)]
print("Addition of two vectors:")
print(vctr_add)


Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Addition of two vectors:
[11 22 33 44 55]


In [15]:
import numpy as np

lst1 = [10, 20, 30, 40, 50]       # 5 términos
lst2 = [1, 2, 3, 4, 5]     # 7 términos

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_sub = vctr1 - vctr2[:len(vctr1)]
print("Subtraction of two vectors:")
print(vctr_sub)


Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 2 3 4 5]
Subtraction of two vectors:
[ 9 18 27 36 45]


In [19]:
import numpy as np

lst1 = [10, 20, 30, 40, 50]
lst2 = [1, 1, 1, 1, 1]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ", vctr_dot)


Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[1 1 1 1 1]
Dot product of two vectors:  150


In [16]:
import numpy as np

lst1 = [10, 20, 30, 40, 50]
lst2 = [2, 2, 2, 2, 2]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector created from a list 1:")
print(vctr1)
print("Vector created from a list 2:")
print(vctr2)

vctr_dot = vctr1.dot(vctr2)
print("Dot product of two vectors: ", vctr_dot)

Vector created from a list 1:
[10 20 30 40 50]
Vector created from a list 2:
[2 2 2 2 2]
Dot product of two vectors:  300
